### ISSUE TITLE
Using from a controller

### ISSUE THREAD

**Issue by sdousley** [jkusa/ember-cli-clipboard#40]
Is there any way to utilise this from a controller, rather than a UI component?

I have a modal that is generated, and has 3 optional buttons, which are setup as ui-button, so can't convert them to copy-button's.

This means that I want to be able to set an action on the button that triggers the copy to clipboard.

**Comment by jkusa** [comment]
Hi @sdousley, no not at the moment. The underlying library, [clipboard.js](https://clipboardjs.com/) requires a selector for listening to click events. This is due to the fact that the browser will only do clipboard copies as a result of a user click.

```js
const clipboard = new ClipboardJS('.btn');
```

If you did this in a click action handler it would be too late.

You could try to register the click handler (via clipboard.js directly) when the modal opens, if you have a hook for that.

Alternatively, you could write your own clipboard click ember action.

```js
document.execCommand('copy');
```

However, you will have to check the support for the browsers you are targeting.
