### ISSUE TITLE
Using index in cliboardTarget

### ISSUE THREAD

**Issue by yagosenhorini** [jkusa/ember-cli-clipboard#45]
Hi,
Is there a way to pass an index on clipboardTarget?

I'm trying to do this:

template:
```hbs
 {{#each apiKeys as |api index|}}
  <strong>{{api.description}}</strong>
  {{em-clipboard api=api index=index}}
  <br />
{{/each}}
```

component-template:
```hbs
 <div class="input-group">
  <input type="text" id={{index}} class="form-control" value={{api.id}} />
  <span class="input-group-btn">
    {{#copy-button
      clipboardTarget=index
      success=(action "onSuccess")
      error=(action "onError")
      classNames="btn btn-default"
    }}
    <i class="fa fa-files-o"></i>
      {{t 'copy'}}
    {{/copy-button}}
  </span>
</div>
```
When I do this, the component renders fine, but when I click on the copybutton, appears this error on the console:
 Failed to execute 'querySelector' on 'Document': '0' is not a valid selector.

How can I fix this?

**Comment by puwelous** [comment]
Hi, I think that the root of your problem is that the `clipboardTarget` requires a selector, not just a number. Use concat helper https://www.emberjs.com/api/ember/release/classes/Ember.Templates.helpers/methods/get?anchor=concat to prefix your target with "#"

```
 <div class="input-group">
  <input type="text" id="{{index}}" class="form-control" value={{api.id}} />
  <span class="input-group-btn">
    {{#copy-button
      clipboardTarget=(concat "#" index)
      success=(action "onSuccess")
      error=(action "onError")
      classNames="btn btn-default"
    }}
    <i class="fa fa-files-o"></i>
      {{t 'copy'}}
    {{/copy-button}}
  </span>
</div>
```

Note: If I were you, I would probably prefix the element ID to have some semantics inside. Otherwise your 
 `<input>` will look in DOM as follows:
`<input type="text" id="0" class="form-control" value={{api.id}} />`. I don't think that "0" is a nice element identifier.

**Comment by yagosenhorini** [comment]
Thanks for the help, man.
It works fine now!
I've changed the input id as you recommended
