### ISSUE TITLE
Convert to Octane for supporting Embroider

### ISSUE THREAD

**Issue by NullVoxPopuli** [jkusa/ember-cli-clipboard#79]
As in intermediary, and for some cleanup:
 I think it'd be cool to convert to:
 - Angle Bracket Syntax
 - Use ember-auto-import for ClipboardJS, and import it directly

I'm working on converting my app's build to embroider, and this addon, because it relies on things defined on `window` is a blocker atm.

**Comment by meirish** [comment]
Bummed that stalebot is so aggressive here - I'd love to see this and the associated PR land.

**Comment by jkusa** [comment]
Hey @meirish, what exactly would you like to see? A lot of what the associated PR included was merged in via #114, except for `ember-auto-import`. At the time `ember-auto-import` + `FastBoot` + `ClipboardJS` didn't seem straight forward. I have recently revisited this, and with a new(er) release of ClipboardJS, I think it should be pretty simple. I hope to have this out shortly.

**Comment by meirish** [comment]
hey @jkusa - apologies for missing that! I saw this and the associated PR closed and wrongly assumed it was missing (I had some build issues after adding `ember-cli-clipboard` but had trouble reproing them - I now think it was caused by something else though). Really love this addon btw - thanks for all of your work on it!

**Comment by meirish** [comment]
Ah I was able to repro - gonna follow up with a new issue.
